linters:
  disable-all: false
  enable-all: true
  disable:
    - prealloc
    - err113
    - forbidigo
    - gochecknoglobals
    - mnd
    - varnamelen
    - funlen
    - depguard
    - cyclop
    - exhaustruct
    - wsl
    - gocritic
    - revive
    - whitespace
    - tagliatelle
    - exportloopref
    - lll
    - gci
    - gofumpt

output:
  formats:
    - { format: colored-line-number }
  print-issued-lines: true
  print-linter-name: true

run:
  timeout: 5m

linters-settings:
  depguard:
    include-go-root: false
    skip-generated: true
    ignored-packages:
      - github.com/fatih/color
      - github.com/manifoldco/promptui

  gosec:
    severity: medium
    exclude:
      - G404 # insecure random number source (rand)
