linters:
  disable-all: false
  enable-all: true
  disable:
    - maligned
    - prealloc
    - err113 # require static error definitions
    - forbidigo # forbid fmt.print*
    - G404 # insecure random number source (rand)
    - gochecknoglobals # no global variables
    - mnd # magic numbers
    - varnamelen # var name length

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

run:
  timeout: 5m

linters-settings:
  depguard:
    packages:
      - github.com/fatih/color
      - github.com/manifoldco/promptui
    list-type: blacklist
    exclude-rules:
      - allow: cmd/x-yapper/main.go
