name: Go Cross-Platform Build and Release
on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23']
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: false
    
    - name: Install dependencies
      run: go mod download
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    
    strategy:
      matrix:
        # Include additional platforms if desired
        # Recommended: Linux (x86, ARM), macOS (Intel, ARM), Windows (x86, x64)
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: linux-amd64
          
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            suffix: linux-arm64
          
          - os: macos-latest
            goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          
          - os: macos-latest
            goos: darwin
            goarch: arm64
            suffix: darwin-arm64
          
          - os: windows-latest
            goos: windows
            goarch: amd64
            suffix: windows-amd64
            ext: .exe
          
          - os: windows-latest
            goos: windows
            goarch: 386
            suffix: windows-x86
            ext: .exe
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false
    
    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        go mod download
        go build -v -o x-yapper-${{ matrix.suffix }}${{ matrix.ext }} ./cmd/x-yapper
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: x-yapper-${{ matrix.suffix }}
        path: x-yapper-${{ matrix.suffix }}${{ matrix.ext }}
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: |
          x-yapper-${{ matrix.suffix }}${{ matrix.ext }}
        generate_release_notes: true

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false
    
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m
    
    - name: Go Vet
      run: go vet ./...
